// simple get products
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";


// for products by id
export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAILURE = "GET_PRODUCT_BY_ID_FAILURE";


// for products by category
export const GET_PRODUCT_BY_CATEGORY_REQUEST = "GET_PRODUCT_BY_CATEGORY_REQUEST";
export const GET_PRODUCT_BY_CATEGORY_SUCCESS = "GET_PRODUCT_BY_CATEGORY_SUCCESS";
export const GET_PRODUCT_BY_CATEGORY_FAILURE = "GET_PRODUCT_BY_CATEGORY_FAILURE";


// for landing page
export const GET_CONFIGS_REQUEST = "GET_CONFIGS_REQUEST";
export const GET_CONFIGS_SUCCESS = "GET_CONFIGS_SUCCESS";
export const GET_CONFIGS_FAILURE = "GET_CONFIGS_FAILURE";

// for login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// for signing out of account
export const SIGN_OUT_REQUEST = "SIGN_OUT_REQUEST";

// search 
export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";

// adding order in orders table upon checkout
export const ADD_ORDER_REQUEST = "ADD_ORDER_REQUEST";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILURE = "ADD_ORDER_FAILURE";

// for ordered_products table
export const ADD_ORDER_ITEM_REQUEST = "ADD_ORDER_ITEM_REQUEST";
export const ADD_ORDER_ITEM_SUCCESS = "ADD_ORDER_ITEM_SUCCESS";
export const ADD_ORDER_ITEM_FAILURE = "ADD_ORDER_ITEM_FAILURE";

// for chart
export const ADD_CART_REQUEST = "ADD_TO_CART";
export const UPDATE_CART_REQUEST = "UPDATE_TO_CART";

// for chart modal
export const OPEN_MODAL_REQUEST = "OPEN_MODAL_REQUEST";
export const CLOSE_MODAL_REQUEST = "CLOSE_MODAL_REQUEST";

// for sign up
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

// no on final popup
export const CLOSE_ORDER_COMPLETE_MODAL_REQUEST= "CLOSE_ORDER_COMPLETE_MODAL_REQUEST";
export const CLOSE_ORDER_COMPLETE_MODAL_SUCCESS= "CLOSE_ORDER_COMPLETE_MODAL_SUCCESS";
export const CLOSE_ORDER_COMPLETE_MODAL_FAILURE= "CLOSE_ORDER_COMPLETE_MODAL_FAILURE";