export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAILURE = "GET_PRODUCT_BY_ID_FAILURE";

export const GET_PRODUCT_BY_CATEGORY_REQUEST = "GET_PRODUCT_BY_CATEGORY_REQUEST";
export const GET_PRODUCT_BY_CATEGORY_SUCCESS = "GET_PRODUCT_BY_CATEGORY_SUCCESS";
export const GET_PRODUCT_BY_CATEGORY_FAILURE = "GET_PRODUCT_BY_CATEGORY_FAILURE";

export const GET_CONFIGS_REQUEST = "GET_CONFIGS_REQUEST";
export const GET_CONFIGS_SUCCESS = "GET_CONFIGS_SUCCESS";
export const GET_CONFIGS_FAILURE = "GET_CONFIGS_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";

export const ADD_ORDER_REQUEST = "ADD_ORDER_REQUEST";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILURE = "ADD_ORDER_FAILURE";

export const ADD_CART_REQUEST = "ADD_TO_CART";
export const UPDATE_CART_REQUEST = "UPDATE_TO_CART";
